### PR TITLE
New package dependency

### PR DESCRIPTION
**Pull request by jredrejo**
We need to add iproute2 as a new dependency to the package due to _ifcfg_

### CODE REVIEW

**Comment by lyw07** [comment]
sorry I realize that I forgot to push the 0.13.3 changelog to the repo. do you think if it's okay that we set this change to 0.13.2 and I can resolve the conflict later? thank you, and sorry for the inconvenience!

**Comment by jredrejo** [comment]
> sorry I realize that I forgot to push the 0.13.3 changelog to the repo. do you think if it's okay that we set this change to 0.13.2 and I can resolve the conflict later? thank you, and sorry for the inconvenience!

No problem, please, push the commit and I will do a rebase

**Comment by lyw07** [comment]
thank you @jredrejo! I just pushed the changelog entry for 0.13.3 to master branch

**Comment by jredrejo** [comment]
@lyw07 I did the rebase and checks have passed, could you review this PR, please?

**Comment by jamalex** [comment]
This looks like a hard dependency -- that could be an issue for those attempting to use the DEB offline? Would adding to "recommended" instead have it be installed if available but not block if it isn't? After https://github.com/learningequality/kolibri/pull/7209, Kolibri will still function fine (just without showing addresses) if ip/ifconfig aren't available.

**Comment by jredrejo** [comment]
> This looks like a hard dependency -- that could be an issue for those attempting to use the DEB offline? Would adding to "recommended" instead lead to it being installed if available but not block if it isn't? After [learningequality/kolibri#7209](https://github.com/learningequality/kolibri/pull/7209), Kolibri will still function fine (just without showing addresses) if ip/ifconfig aren't available.

`iproute2` is available in any recent Debian based distribution. The problem appeared only in slimmed envirnoments as Docker.
In fact, `ip` was set to replace  `ifconfig` (and `route`) several  years ago.
Anyway, if [learningequality/kolibri#7209](https://github.com/learningequality/kolibri/pull/7209) solves it, I am always happy to remove dependencies and make things simpler

**Pull request merged**
