### PR TITLE
Fix systemd shutdown, implement "restart", add back Trusty support

### PR DESCRIPTION
**Pull request by benjaoming**
Follow-up on #92

Released on kolibri-proposed

* "su" on Ubuntu 14.04, "runuser" for the others
* Restore Trusty support
* Fix `systemctl restart kolibri` and `service kolibri restart`

### CODE REVIEW

**Comment by benjaoming** [comment]
Tested on Ubuntu Server 18.04 :heavy_check_mark:

**Comment by benjaoming** [comment]
@JamesKainer would you be able to use the kolibri-proposed PPA to test this on Raspbian?

https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed

You have to specify the dist name for apt sources because `apt-add-repository` won't find any Debian dists on Launchpad:

```
sudo apt-get install dirmngr
sudo su -c 'echo "deb http://ppa.launchpad.net/learningequality/kolibri-proposed/ubuntu bionic main" > /etc/apt/sources.list.d/learningequality-ubuntu-kolibri.list'
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys DC5BAA93F9E4AE4F0411F97C74F88ADB3194DD81
sudo apt-get update
sudo apt-get install kolibri
```

**Comment by JamesKainer** [comment]
@benjaoming of course! I'll try it out today and let you know how it goes. Thanks for working on this.

**Comment by JamesKainer** [comment]
I just did a fresh install with only an apt-get update/upgrade and your instructions. The shutdown time is 23 seconds. It looks like the 90s issue is fixed! Is there a zeroconf disable option in this build so I can bring that time down from 23s?

**Comment by benjaoming** [comment]
Thanks so much for testing @JamesKainer !

Will have a test on Ubuntu 14.04 and 16.04 to verify, and then I think it's good to go.

**Comment by benjaoming** [comment]
It's release as 0.13.2-0ubuntu2 in `kolibri-proposed` btw, meaning that the final 0.13.2 release is included now.

**Comment by JamesKainer** [comment]
Thanks for all of the great work Benjamin.

**Comment by benjaoming** [comment]
The latest build in `kolibri-proposed` is now 0.13.2-0ubuntu4

**Pull request merged**
