### PR TITLE
update changelog for kolibri 0.12.3 release

### PR DESCRIPTION
**Pull request by lyw07**
changelog updates for kolibri 0.12.3 release

### CODE REVIEW

**Comment by benjaoming** [comment]
Great! Feel free to add for example a link to the upstream timeline. The Changelog shows up in the Ubuntu Update Manager etc.

**Comment by lyw07** [comment]
@benjaoming could you please give an example? I'm sorry I'm not sure I understand it correctly. Thank you!

**Comment by benjaoming** [comment]
image

**Comment by lyw07** [comment]
Do you mean something like this?:
```
* New upstream release <https://github.com/learningequality/kolibri/releases/tag/v0.12.3>
```

**Comment by benjaoming** [comment]
@lyw07 it's very free text, so we can even put "Huzza, we have a new release! The release notes are here: https://github.com/learningequality/kolibri/releases/tag/v0.12.3" :small_airplane: 

I guess for future release notes it's great to put a link or a copy-paste of the list, depending on what's most elegant and presentable.

**Comment by lyw07** [comment]
makes sense to me. thank you for the explanation! @benjaoming

**Pull request merged**
