### PR TITLE
Dropping Python 3.7 constraint for 0.11.1

### PR DESCRIPTION
**Pull request by benjaoming**
CC: @lyw07 

Ref: https://github.com/learningequality/kolibri/issues/4548

### CODE REVIEW

**Comment by benjaoming** [comment]
Released a test build: https://launchpad.net/~learningequality/+archive/ubuntu/kolibri-proposed/

**Comment by lyw07** [comment]
Thank you for getting the changes in! 

I think in debian/control we set the python3 dependency to be under 3.7: https://github.com/learningequality/kolibri-installer-debian/blob/master/debian/control#L30,
I assume you made the change from `<< 3.7` to `<= 3.7` but somehow it doesn't get into the PR?

**Comment by benjaoming** [comment]
# facepalm

Yes, thanks :) I made a `uupdate` mistake and overwrote my changes :)

**Comment by benjaoming** [comment]
Please don't merge this btw.. it contains changelog stuff that is just for a pre-release.

**Comment by benjaoming** [comment]
Released as 0.11.1 in stable PPA. Changelog amended accordingly. Because I made a bad release (w/ wrong upstream source tarball), there will be a `0.11.1-0ubuntu2` release in `kolibri-proposed` which corresponds to `0.11.1-0ubuntu1` in the stable PPA and the .deb on our website.

**Pull request merged**
